name: maydan
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.9+10

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  flutter_svg: ^1.1.6

  #service locator
  get_it: ^7.2.0

  #api request handler
  http: ^0.13.5

  shared_preferences: ^2.0.15

  flutter_swiper_view: ^1.1.8

  image_picker: ^0.8.6
  flutter_native_image: ^0.0.6
  photo_view: ^0.14.0

  url_launcher: ^6.1.7
  share_plus: ^6.3.0

  pull_to_refresh_flutter3: ^2.0.1
  get: ^4.6.5

  # Firebase
  firebase_core: ^2.4.0
  firebase_messaging: ^14.2.0

  # Multi-Languages
  flutter_localizations:
    sdk: flutter

  intl: ^0.17.0
  provider: ^6.0.5

  flutter_native_splash: ^2.2.17

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter_native_splash:
  color: "#79a207"
  image: "assets/background.png"
  branding_mode: bottom
  android_12:
    image: assets/background.png
    icon_background_color: "#79a207"
    image_dark: assets/background.png
    icon_background_color_dark: "#79a207"

  android: true
  ios: true

flutter:

  generate: true
  uses-material-design: true

  assets:
    - assets/
  fonts:
    - family: Myraid
      fonts:
        - asset: fonts/myriadpro.OTF