name: maydan
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.2.2+31

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  flutter_svg: ^2.0.3

  #service locator
  get_it: ^7.2.0

  #api request handler
  http: ^1.1.2

  shared_preferences: ^2.0.15

  flutter_swiper_view: ^1.1.8

  image_picker: ^1.0.5
  flutter_native_image: ^0.0.6
  photo_view: ^0.14.0

  url_launcher: ^6.1.7
  share_plus: ^7.0.2

  pull_to_refresh_flutter3: ^2.0.1
  get: ^4.6.5

  # Firebase
  firebase_core: ^2.4.0
  firebase_messaging: ^14.2.0
  firebase_analytics: ^10.5.0

  # Multi-Languages
  flutter_localizations:
    sdk: flutter

  intl: ^0.18.1
  provider: ^6.0.5

  flutter_native_splash: ^2.2.17

  flutter_staggered_grid_view: ^0.4.1
  appsflyer_sdk: ^6.10.3

  flutter_facebook_auth: ^6.0.3
  sign_in_with_apple: ^5.0.0

  flutter_dotenv: ^5.1.0
  package_info_plus: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter_native_splash:
  color: "#FFFFFF"
  image: "assets/background_1.png"
  branding_mode: bottom
  android_12:
    image: assets/background_1.png
    icon_background_color: "#FFFFFF"
    image_dark: assets/background_1.png
    icon_background_color_dark: "#FFFFFF"

  android: true
  ios: true

flutter:

  generate: true
  uses-material-design: true

  assets:
    - assets/
    - .env
  fonts:
    - family: Myraid
      fonts:
        - asset: fonts/myriadpro.OTF